language: node_js
node_js:
- 6
notifications:
  slack:
    secure: CB8GVBp2aK2qCsN5NzqWXyoLDLsvqq0mFgACRwj9yMmeufk3GneJZ48KfRvhx8zARzZolOXF60T3N5YYagYOYOPgI42bgGTO68UOA5iRnIhBQWIHQcZOZ2XXd0H8J+je6d2Q/TwzCz9eR3ON970M1zZYLY8rupfmKEE3ahjYPIYNpKUumMyT1LSYZXPG1MY4ZNtE5QM/woRxjkQ8tr8O2/+FRhkGH9K5D2+Agtyc4pDIo2cx1TklIu2hHkp7nf21k0lttLLYcuhUD72x7+czpzb2uwFwptu4foDjVj3FkwsqJlfGwmfKhCfzrW0VFM5TbrEJAhN2FrYE5CaH897NSFFC/038ib3U3Y0UCpKqy1RyO8P+9ES4PqlWnUlxK0CWTpb5HcU7TOQUcWUrFDaL6hAfAC8/rdBSKHQV6bxsp2W5jujf180s7nG00MacUbvJgmlhCFn70zJ31lFcm21yt6OzWKzb5tq+lD6cqPBYEyW5UyeZMVqxpb2W9Dpy137fWnQbPqf0YMn1NPuXGR+kKfhjNEEBzcWAnHaZC3HmYBqfYw/FLMKysjduzX3+KUoRAHDdFmQHDn560ZqzBF0q7jfn2T0PIOzxXoDrM0vTYQKJa8XMcUrg+SKc047KHYTkIDxbVVzukPArlLqnOrcsOSNd966GgwKw8YASZp348VE=
